[workspace]
name = "esp32c6-zener"
repository = "github.com/iu3qez/esp32c6"
pcb-version = "0.3"
vendor = ["github.com/diodeinc/registry/**"]

[board]
name = "C6MacroSwitch"
path = "C6MacroSwitch.zen"
description = "ESP32-C6 Zigbee battery-powered macro switch"

[dependencies.indirect]
"gitlab.com/kicad/libraries/kicad-footprints@9" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-packages3D@9" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols@9" = "9.0.3"

[access]
allow = ["*"]
